# -*- coding: utf-8 -*-
"""football.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fn8mvJ0euM1zoy4L6dStMRqJVe4DeBBu

# ⚽ **Analyse du Football International (1872–2025)**
### Projet — Exploration & Statistiques
"""



import pandas as pd
import kagglehub
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick

"""# Charger les Données

Téléchargement
"""

path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")
print("Path:", path)

"""Chargement"""

results      = pd.read_csv(f"{path}/results.csv")
shootouts    = pd.read_csv(f"{path}/shootouts.csv")
goalscorers  = pd.read_csv(f"{path}/goalscorers.csv")
former_names = pd.read_csv(f"{path}/former_names.csv")

dfs = {
    "results":      results,
    "shootouts":    shootouts,
    "goalscorers":  goalscorers,
    "former_names": former_names,
}

print(dfs)

"""Inspection initiale"""

for name, df in dfs.items():
    print(f"\n{'='*55}")
    print(f"  {name.upper()}")
    print(f"{'='*55}")
    print(f"  Lignes × Colonnes : {df.shape}")
    print(f"  Colonnes          : {list(df.columns)}")
    print(f"\n  Types de données :")
    print(df.dtypes.to_string())
    print(f"\n  Valeurs nulles par colonne :")
    print(df.isnull().sum().to_string())
    print(f"\n  Doublons exacts : {df.duplicated().sum()}")
    print(f"\n  3 premières lignes :")
    print(df.head(3).to_string())

"""# Nettoyage

Conversion des dates
"""

for name, df in dfs.items():
    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        invalides = df["date"].isnull().sum()
        if invalides:
            print(f"[{name}] ⚠️  {invalides} dates invalides → seront supprimées")
            dfs[name] = df.dropna(subset=["date"])

"""Suppression des doublons"""

for name, df in dfs.items():
    avant = len(df)
    dfs[name] = df.drop_duplicates()
    supprimes = avant - len(dfs[name])
    if supprimes:
        print(f"[{name}] 🗑️  {supprimes} doublons supprimés")

"""Nettoyage des espaces dans les colonnes texte"""

cols_texte = {
    "results":      ["home_team", "away_team", "tournament", "city", "country"],
    "shootouts":    ["home_team", "away_team", "winner", "first_shooter"],
    "goalscorers":  ["home_team", "away_team", "team", "scorer"],
    "former_names": ["current", "former"],
}
for name, cols in cols_texte.items():
    for col in cols:
        if col in dfs[name].columns:
            dfs[name][col] = dfs[name][col].str.strip()

"""Normalisation des colonnes booléennes"""

for col in ["neutral", "own_goal", "penalty"]:
    for name, df in dfs.items():
        if col in df.columns:
            dfs[name][col] = df[col].astype(str).str.strip().str.upper().map(
                {"TRUE": True, "FALSE": False, "1": True, "0": False}
            )

"""Vérification des scores non négatifs"""

neg_domicile = (dfs["results"]["home_score"] < 0).sum()
neg_exterieur = (dfs["results"]["away_score"] < 0).sum()
if neg_domicile or neg_exterieur:
    print(f"[results] ⚠️  Scores négatifs : domicile={neg_domicile}, extérieur={neg_exterieur}")
else:
    print("[results] ✅ Aucun score négatif détecté")

"""Conversion des dates de début/fin dans former_names"""

for col in ["start_date", "end_date"]:
    if col in dfs["former_names"].columns:
        dfs["former_names"][col] = pd.to_datetime(
            dfs["former_names"][col], errors="coerce"
        )

"""**RÉAFFECTATION DES VARIABLES NETTOYÉES**"""

results      = dfs["results"]
shootouts    = dfs["shootouts"]
goalscorers  = dfs["goalscorers"]
former_names = dfs["former_names"]

"""Résumé final"""

print("\n" + "="*55)
print("  RÉSUMÉ FINAL — DONNÉES NETTOYÉES")
print("="*55)
for name, df in dfs.items():
    print(f"  {name:<15} → {df.shape[0]:>6,} lignes  |  {df.shape[1]} colonnes  |  "
          f"{df.isnull().sum().sum()} valeurs nulles restantes")
print("\n✅ Nettoyage terminé. Les DataFrames sont prêts.\n")

"""* Shootouts a 429 valeurs nulles mais sur seulement 675 lignes"""

print(shootouts)

"""VÉRIFICATION : NaN dans first_shooter"""

# Séparer les lignes avec et sans first_shooter
avec_first = shootouts[shootouts["first_shooter"].notna()]
sans_first = shootouts[shootouts["first_shooter"].isna()]

print(f"  Enregistrements AVEC first_shooter : {len(avec_first)}")
print(f"  Enregistrements SANS first_shooter : {len(sans_first)}")

# Vérifier si ces lignes ont quand même un gagnant
print(f"\n  Parmi les NaN dans first_shooter...")
print(f"  → Ont-ils un 'winner' enregistré ?")
print(sans_first["winner"].value_counts(dropna=False).to_string())

# Afficher quelques exemples
print(f"\n  Exemples de lignes avec first_shooter = NaN :")
print(sans_first.head(10).to_string())

"""REMPLACEMENT DES NaN DANS first_shooter

"""

# Copie de travail — ne jamais modifier shootouts directement
shootouts_clean = shootouts.copy()
shootouts_clean["first_shooter"] = shootouts_clean["first_shooter"].fillna("Inconnu")

# Ajout d'une colonne indicatrice pour distinguer les valeurs connues des inconnues
shootouts_clean["first_shooter_connu"] = shootouts["first_shooter"].notna()

# Vérification finale
print("  Vérification après remplacement :")
print(f"  NaN restants dans first_shooter      : {shootouts_clean['first_shooter'].isna().sum()}")
print(f"  Enregistrements avec valeur connue   : {shootouts_clean['first_shooter_connu'].sum()}")
print(f"  Enregistrements avec valeur inconnue : {(~shootouts_clean['first_shooter_connu']).sum()}")

# Mise à jour dans le dictionnaire principal
dfs["shootouts"] = shootouts_clean

"""* Analyse des valeurs manquantes dans la colonne 'first_shooter' :
Sur 675 enregistrements, 429 ont un NaN dans cette colonne (63.5%). Après vérification, tous ces enregistrements possèdent bien un 'winner', ce qui confirme que les tirs au but ont bien eu lieu.
* L'absence de données s'explique par un manque de documentation historique : les matchs concernés datent majoritairement des années 1960-1970, une époque où le suivi statistique détaillé n'était pas encore systématique.

* **DÉCISION :** on conserve le DataFrame original intact et on travaille sur une copie. Remplacer les NaN directement serait risqué car on introduirait une valeur inventée là où l'information est simplement absente.

DIAGNOSTIC DES VALEURS NULLES : results & goalscorers
"""

# Analyse détaillée de results
print("=" * 55)
print("  RESULTS — Détail des valeurs nulles")
print("=" * 55)
nuls_results = results.isnull().sum()
nuls_results = nuls_results[nuls_results > 0]
for col, n in nuls_results.items():
    pct = (n / len(results)) * 100
    print(f"  {col:<20} → {n:>5} nuls  ({pct:.2f}%)")

print(f"\n  Exemples de lignes avec des nuls :")
print(results[results.isnull().any(axis=1)].head(5).to_string())

# Analyse détaillée de goalscorers
print("\n" + "=" * 55)
print("  GOALSCORERS — Détail des valeurs nulles")
print("=" * 55)
nuls_goals = goalscorers.isnull().sum()
nuls_goals = nuls_goals[nuls_goals > 0]
for col, n in nuls_goals.items():
    pct = (n / len(goalscorers)) * 100
    print(f"  {col:<20} → {n:>5} nuls  ({pct:.2f}%)")

print(f"\n  Exemples de lignes avec des nuls :")
print(goalscorers[goalscorers.isnull().any(axis=1)].head(5).to_string())

"""**ANALYSE CONTEXTUELLE DES VALEURS NULLES**

Vérifier les matchs sans score dans results
"""

print("=" * 55)
print("  RESULTS — Matchs sans score")
print("=" * 55)
sans_score = results[results["home_score"].isna()]
print(f"  Total matchs sans score : {len(sans_score)}")
print(f"\n  Répartition par tournoi :")
print(sans_score["tournament"].value_counts().head(10).to_string())
print(f"\n  Répartition temporelle :")
print(f"  Année min : {sans_score['date'].dt.year.min()}")
print(f"  Année max : {sans_score['date'].dt.year.max()}")
print(f"\n  Exemples :")
print(sans_score.head(5).to_string())

"""Vérifier les buts sans buteur dans goalscorers"""

print("\n" + "=" * 55)
print("  GOALSCORERS — Buts sans buteur")
print("=" * 55)
sans_buteur = goalscorers[goalscorers["scorer"].isna()]
print(f"  Total buts sans buteur : {len(sans_buteur)}")
print(f"\n  Sont-ils des own goals ?")
print(sans_buteur["own_goal"].value_counts(dropna=False).to_string())
print(f"\n  Sont-ils des penaltys ?")
print(sans_buteur["penalty"].value_counts(dropna=False).to_string())

"""Vérifier les buts sans minute"""

print("\n" + "=" * 55)
print("  GOALSCORERS — Buts sans minute")
print("=" * 55)
sans_minute = goalscorers[goalscorers["minute"].isna()]
print(f"  Total buts sans minute : {len(sans_minute)}")
print(f"\n  Répartition temporelle :")
print(f"  Année min : {sans_minute['date'].dt.year.min()}")
print(f"  Année max : {sans_minute['date'].dt.year.max()}")
print(f"\n  Exemples :")
print(sans_minute.head(5).to_string())

"""**TRAITEMENT DES VALEURS NULLES : results & goalscorers**"""

# RESULTS — 72 matchs sans score
# Ces matchs peuvent être des matchs abandonnés, annulés ou mal documentés.
# On conserve l'original et on crée une copie sans ces lignes pour les analyses
# qui nécessitent des scores (calcul de moyennes, tendances, etc.)
results_original = results.copy()
results_clean = results.dropna(subset=["home_score", "away_score"]).copy()

print("=" * 55)
print("  RESULTS")
print("=" * 55)
print(f"  Lignes original : {len(results_original)}")
print(f"  Lignes clean    : {len(results_clean)}")
print(f"  Matchs écartés  : {len(results_original) - len(results_clean)}")

# GOALSCORERS — 11 buts sans buteur
# Ni own goals ni penaltys — l'identité du buteur est simplement inconnue.
# On conserve l'original et dans la copie on remplace par "Inconnu"
# pour maintenir la cohérence avec le traitement de first_shooter.
goalscorers_original = goalscorers.copy()
goalscorers_clean = goalscorers.copy()
goalscorers_clean["scorer"] = goalscorers_clean["scorer"].fillna("Inconnu")
goalscorers_clean["scorer_connu"] = goalscorers["scorer"].notna()

# GOALSCORERS — 184 buts sans minute
# Tous entre 1960 et 1997 — absence de documentation historique.
# On conserve les NaN car -1 ou 0 induiraient en erreur les analyses temporelles.
# On ajoute uniquement une colonne indicatrice.
goalscorers_clean["minute_connue"] = goalscorers["minute"].notna()

print("\n" + "=" * 55)
print("  GOALSCORERS")
print("=" * 55)
print(f"  Lignes original            : {len(goalscorers_original)}")
print(f"  Buts avec buteur inconnu   : {(~goalscorers_clean['scorer_connu']).sum()}")
print(f"  Buts avec minute inconnue  : {(~goalscorers_clean['minute_connue']).sum()}")
print(f"  NaN restants dans scorer   : {goalscorers_clean['scorer'].isna().sum()}")
print(f"  NaN restants dans minute   : {goalscorers_clean['minute'].isna().sum()}")

# Mise à jour dans le dictionnaire principal
dfs["results"]     = results_clean
dfs["goalscorers"] = goalscorers_clean

print("\n✅ Traitement terminé. Récapitulatif final :")
for name, df in dfs.items():
    print(f"  {name:<15} → {df.shape[0]:>6,} lignes  |  "
          f"{df.isnull().sum().sum()} valeurs nulles restantes")

"""# Analyse Exploratoire des Données (EDA)"""

# CONFIGURATION GÉNÉRALE DES GRAPHIQUES
sns.set_theme(style="darkgrid")
plt.rcParams["figure.figsize"] = (12, 6)
plt.rcParams["font.size"] = 12

"""Analyse Globale de L'avantage À Domicile"""

# Création des colonnes de résultat
results_clean["resultat"] = results_clean.apply(
    lambda row: "Domicile" if row["home_score"] > row["away_score"]
    else ("Extérieur" if row["home_score"] < row["away_score"]
    else "Nul"), axis=1
)

# Exclure les matchs joués sur terrain neutre pour l'analyse domicile/extérieur
results_neutres  = results_clean[results_clean["neutral"] == True]
results_domicile = results_clean[results_clean["neutral"] == False]

print("=" * 55)
print("  ANALYSE GLOBALE — AVANTAGE À DOMICILE")
print("=" * 55)
print(f"  Total matchs analysés       : {len(results_clean):>7,}")
print(f"  Matchs sur terrain neutre   : {len(results_neutres):>7,}")
print(f"  Matchs avec domicile/visiteur: {len(results_domicile):>7,}")

"""Statistiques Globales"""

# Distribution des résultats — tous matchs
dist_total = results_clean["resultat"].value_counts(normalize=True) * 100
print(f"\n  Distribution des résultats (tous matchs) :")
for res, pct in dist_total.items():
    print(f"  {res:<15} → {pct:.1f}%")

# Distribution des résultats — terrain non neutre uniquement
dist_domicile = results_domicile["resultat"].value_counts(normalize=True) * 100
print(f"\n  Distribution des résultats (terrain non neutre) :")
for res, pct in dist_domicile.items():
    print(f"  {res:<15} → {pct:.1f}%")

# Moyenne de buts domicile vs extérieur
print(f"\n  Moyenne de buts (terrain non neutre) :")
print(f"  Domicile   → {results_domicile['home_score'].mean():.2f} buts/match")
print(f"  Extérieur  → {results_domicile['away_score'].mean():.2f} buts/match")

"""Évolution par Décennie"""

# Créer une colonne décennie
results_domicile = results_domicile.copy()
results_domicile["decennie"] = (results_domicile["date"].dt.year // 10 * 10).astype(str) + "s"

# Taux de victoire à domicile par décennie
taux_par_decennie = (
    results_domicile.groupby("decennie")["resultat"]
    .apply(lambda x: (x == "Domicile").sum() / len(x) * 100)
    .reset_index()
)
taux_par_decennie.columns = ["decennie", "taux_victoire_domicile"]

print(f"\n  Taux de victoire à domicile par décennie :")
print(taux_par_decennie.to_string(index=False))

"""Visualisations"""

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.suptitle("Analyse globale de l'avantage à domicile — Football international",
             fontsize=15, fontweight="bold", y=1.02)

# Graphique 1 — Distribution des résultats (terrain non neutre)
# couleurs = ["#2ecc71", "#e74c3c", "#95a5a6"]
couleurs = ["#185FA5", "#85B7EB", "#EF9F27"]
axes[0].pie(
    dist_domicile.values,
    labels=dist_domicile.index,
    autopct="%1.1f%%",
    colors=couleurs,
    startangle=90
)
axes[0].set_title("Résultats — Terrain non neutre", fontweight="bold")


# Graphique 2 — Moyenne de buts domicile vs extérieur
buts = ["Domicile", "Extérieur"]
moyennes = [results_domicile["home_score"].mean(), results_domicile["away_score"].mean()]
barres = axes[1].bar(buts, moyennes, color=["#185FA5", "#85B7EB"], width=0.5)
axes[1].set_title("Moyenne de buts par match", fontweight="bold")
axes[1].set_ylabel("Buts / match")
axes[1].set_ylim(0, 2.5)
for barre, val in zip(barres, moyennes):
    axes[1].text(barre.get_x() + barre.get_width()/2, barre.get_height() + 0.03,
                 f"{val:.2f}", ha="center", fontweight="bold")


# Graphique 3 — Évolution du taux de victoire à domicile par décennie
axes[2].plot(
    taux_par_decennie["decennie"],
    taux_par_decennie["taux_victoire_domicile"],
    marker="o", color="#3498db", linewidth=2.5, markersize=7
)
axes[2].axhline(y=50, color="gray", linestyle="--", alpha=0.7, label="50% (référence)")
axes[2].set_title("Évolution par décennie", fontweight="bold")
axes[2].set_ylabel("Taux de victoire à domicile (%)")
axes[2].set_xlabel("Décennie")
axes[2].tick_params(axis="x", rotation=45)
axes[2].legend()
axes[2].set_ylim(30, 70)

plt.tight_layout()
plt.savefig("avantage_domicile_global.png", dpi=150, bbox_inches="tight")
plt.show()
print("\n✅ Graphiques sauvegardés.")













"""# Coupe du Monde FIFA

# UEFA Champions League
"""

# ============================================================
# 💾 SAUVEGARDE DES DONNÉES NETTOYÉES EN CSV
# Ajouter ces cellules à la fin de la section "Nettoyage"
# ============================================================

import os

# Dossier de sortie
output_dir = "data_clean"
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde de chaque DataFrame nettoyé
results_clean.to_csv(f"{output_dir}/results_clean.csv", index=False)
shootouts_clean.to_csv(f"{output_dir}/shootouts_clean.csv", index=False)
goalscorers_clean.to_csv(f"{output_dir}/goalscorers_clean.csv", index=False)
former_names.to_csv(f"{output_dir}/former_names.csv", index=False)

# Sauvegarde des données EDA déjà calculées
results_domicile.to_csv(f"{output_dir}/results_domicile.csv", index=False)
taux_par_decennie.to_csv(f"{output_dir}/taux_par_decennie.csv", index=False)

print("✅ CSV sauvegardés dans le dossier 'data_clean/' :")
for f in os.listdir(output_dir):
    taille = os.path.getsize(f"{output_dir}/{f}") / 1024
    print(f"  📄 {f}  ({taille:.1f} KB)")
